/**
 * Report Generator
 * 
 * Generates markdown reports from daily crawl data.
 * Creates both individual site reports and daily overview reports.
 */

import type { DailyReport, SiteRecord, PageSummary } from '../types/index';
import { formatBytes, truncate } from '../utils/index';

/**
 * Generate a markdown daily report.
 */
export function generateDailyMarkdown(report: DailyReport): string {
  const lines: string[] = [];

  lines.push(`# 🌐 Web Explorer - Daily Report: ${report.date}`);
  lines.push('');
  lines.push(`> Generated at: ${report.generatedAt}`);
  lines.push('');

  // Summary
  lines.push('## 📊 Summary');
  lines.push('');
  lines.push(report.daySummary);
  lines.push('');

  // Stats
  lines.push('## 📈 Statistics');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Pages Crawled | ${report.totalPagesCrawled} |`);
  lines.push(`| New Sites Discovered | ${report.newSitesDiscovered} |`);
  lines.push(`| Total Attempted | ${report.stats.totalAttempted} |`);
  lines.push(`| Success Rate | ${report.stats.totalAttempted > 0 ? Math.round((report.stats.successfulCrawls / report.stats.totalAttempted) * 100) : 0}% |`);
  lines.push(`| Avg Response Time | ${report.stats.avgResponseTimeMs}ms |`);
  lines.push(`| Total Data | ${formatBytes(report.stats.totalDataBytes)} |`);
  lines.push(`| Duration | ${report.stats.durationSeconds.toFixed(1)}s |`);
  lines.push(`| Categories | ${report.stats.categoriesFound.join(', ')} |`);
  lines.push('');

  // Pages by category
  lines.push('## 📂 Content by Category');
  lines.push('');

  for (const [category, summaries] of Object.entries(report.byCategory)) {
    lines.push(`### ${getCategoryEmoji(category)} ${category} (${summaries.length} pages)`);
    lines.push('');

    for (const summary of summaries) {
      lines.push(`#### [${truncate(summary.title, 80)}](${summary.url})`);
      lines.push('');
      lines.push(`> Security Score: ${getSecurityBadge(summary.securityScore)} | Keywords: ${summary.topKeywords.join(', ')}`);
      lines.push('');
      lines.push(summary.shortSummary);
      lines.push('');
      lines.push('<details>');
      lines.push('<summary>Detailed Summary</summary>');
      lines.push('');
      lines.push(summary.detailedSummary);
      lines.push('');
      lines.push('</details>');
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  // Footer
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [Web Explorer](https://github.com/curvelog/navigation-in-the-web) - Automated Web Discovery System*`);

  return lines.join('\n');
}

/**
 * Generate a markdown report for a specific site.
 */
export function generateSiteMarkdown(record: SiteRecord): string {
  const lines: string[] = [];

  lines.push(`# 🌐 Site Report: ${record.domain}`);
  lines.push('');
  lines.push(`> ${record.description || 'No description available'}`);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| Domain | [${record.domain}](${record.baseUrl}) |`);
  lines.push(`| Status | ${record.status} |`);
  lines.push(`| First Discovered | ${record.firstDiscovered} |`);
  lines.push(`| Last Crawled | ${record.lastCrawled} |`);
  lines.push(`| Times Crawled | ${record.crawlCount} |`);
  lines.push(`| Avg Security Score | ${getSecurityBadge(record.avgSecurityScore)} |`);
  lines.push(`| Categories | ${record.categories.join(', ')} |`);
  lines.push('');

  if (record.summaryHistory.length > 0) {
    lines.push('## Summary History');
    lines.push('');

    for (const entry of record.summaryHistory.slice().reverse()) {
      lines.push(`### ${entry.date}`);
      lines.push('');
      lines.push(entry.summary);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Generate the main index markdown file.
 */
export function generateIndexMarkdown(
  dates: Array<{ date: string; pageCount: number; categories: string[] }>,
  totalSites: number
): string {
  const lines: string[] = [];

  lines.push('# 🌐 Web Explorer - Index');
  lines.push('');
  lines.push('> Automated daily web discovery and summarization system');
  lines.push('');
  lines.push(`**Total Days Recorded:** ${dates.length} | **Total Sites Discovered:** ${totalSites}`);
  lines.push('');

  if (dates.length === 0) {
    lines.push('*No reports generated yet. The first crawl will run automatically.*');
  } else {
    lines.push('## 📅 Daily Reports');
    lines.push('');
    lines.push('| Date | Pages | Categories |');
    lines.push('|------|-------|------------|');

    for (const entry of dates) {
      const catStr = entry.categories.map(c => getCategoryEmoji(c) + c).join(', ');
      lines.push(`| [${entry.date}](/day/${entry.date}) | ${entry.pageCount} | ${catStr} |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Powered by [Web Explorer](https://github.com/curvelog/navigation-in-the-web)*');

  return lines.join('\n');
}

/** Get emoji for a content category */
function getCategoryEmoji(category: string): string {
  const emojis: Record<string, string> = {
    'Technology': '💻',
    'Science': '🔬',
    'News': '📰',
    'Business': '💼',
    'Health': '🏥',
    'Education': '📚',
    'Entertainment': '🎬',
    'Culture': '🎨',
    'Environment': '🌱',
    'Politics': '🏛️',
    'General': '📋',
  };
  return emojis[category] || '📋';
}

/** Get a security score badge */
function getSecurityBadge(score: number): string {
  if (score >= 80) return `🟢 ${score}/100`;
  if (score >= 60) return `🟡 ${score}/100`;
  if (score >= 40) return `🟠 ${score}/100`;
  return `🔴 ${score}/100`;
}
